/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as HomeIndexImport } from "./routes/_home/index";
import { Route as AuthSignUpImport } from "./routes/auth/sign-up";
import { Route as AuthLoginImport } from "./routes/auth/login";

// Create/Update Routes

const HomeIndexRoute = HomeIndexImport.update({
  id: "/_home/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AuthSignUpRoute = AuthSignUpImport.update({
  id: "/auth/sign-up",
  path: "/auth/sign-up",
  getParentRoute: () => rootRoute,
} as any);

const AuthLoginRoute = AuthLoginImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/sign-up": {
      id: "/auth/sign-up";
      path: "/auth/sign-up";
      fullPath: "/auth/sign-up";
      preLoaderRoute: typeof AuthSignUpImport;
      parentRoute: typeof rootRoute;
    };
    "/_home/": {
      id: "/_home/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof HomeIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/auth/login": typeof AuthLoginRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/": typeof HomeIndexRoute;
}

export interface FileRoutesByTo {
  "/auth/login": typeof AuthLoginRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/": typeof HomeIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/_home/": typeof HomeIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/auth/login" | "/auth/sign-up" | "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/auth/login" | "/auth/sign-up" | "/";
  id: "__root__" | "/auth/login" | "/auth/sign-up" | "/_home/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthSignUpRoute: typeof AuthSignUpRoute;
  HomeIndexRoute: typeof HomeIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  HomeIndexRoute: HomeIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/auth/login",
        "/auth/sign-up",
        "/_home/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/_home/": {
      "filePath": "_home/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
